### ISSUE TITLE
小程序中，Filter.Item 被 fixed 在页面上，我 scroll up & down 的时候跟着跑

### ISSUE THREAD

**Issue by wujun4code** [AnnaSearl/annar#57]
## 截图
![image](https://user-images.githubusercontent.com/5119542/101604082-6c562b00-3a3b-11eb-92f1-151547039fdd.png)
![image](https://user-images.githubusercontent.com/5119542/101604133-7aa44700-3a3b-11eb-98f1-58f03fd5f632.png)

```js
 <Frame grayBg style={{ overflow: 'hidden' }}>
            <Block title={state.pages.homepage.categoryGroup.group.title}>
              <Filter style={{ zIndex: 5, position: 'relative' }}>
                <Filter.Item
                  title='品类'
                  value={value}
                  options={options}
                  // onChange={e => setValue(e.value)}
                />
              </Filter>
            </Block>
          </Frame>
```

源头是因为
```css

  .anna-filter-content {
    z-index: 1;
    position: fixed;
    top: unset;
    bottom: unset;
    height: 100%;
    width: 100%;
    overflow: hidden;
    transition: height 0.3s ease; }
```
